#pragma once
#include "CoreMinimal.h"
#include "ESBZGameMachineStateError.generated.h"

UENUM(BlueprintType)
enum class ESBZGameMachineStateError : uint8 {
    HostDisconnected,
    HostFailedToStartLoading,
    DropInIntoEndedMission,
    WrongGameVersion,
    NoMatchingServerVersion,
    MatchmakingError,
    HostBeaconDisconnected,
    ActionBeaconTimeout,
    TravelToHostTimeout,
    StartTravellingHandshakeFailed,
    MissionEnded,
    InvalidReturnToMainMenu,
    HostMigrationFailed,
    WrongLevel,
    SteamNotSignedIn,
    EOSNotSignedIn,
    PSNNotSignedIn,
    XboxLiveNotSignedIn,
    PremiumAccountEligibilityCheck,
    NetworkNoConnection,
    FailedToFetchRequiredAccelByteData,
    LostConnectionToMatchMakingService,
    NebulaLoginConnectionFailed,
    NebulaLoginConnectionFailedAlreadyLinked,
    NebulaLoginFailed,
    NebulaLoginLinking,
    NebulaLoginLinkingOtherXbox,
    NebulaLoginWrongCreds,
    Unknown,
    FailedToResumeGame,
    PartySessionIsFull,
    PartySessionDoesNotExist,
    PartySessionAlreadyInSession,
    PartySessionInvalidFriendship,
    PartySessionInvalidCode,
    PartySessionMaxActiveSessionReached,
    PartySessionInvalidJoinability,
    PartySessionInactiveTimeout,
    PartySessionMemberBlock,
    GameSessionIsFull,
    GameSessionDoesNotExist,
    GameSessionAlreadyInSession,
    GameSessionInvalidFriendship,
    GameSessionInvalidCode,
    GameSessionMaxActiveSessionReached,
    GameSessionInvalidJoinability,
    GameSessionInactiveTimeout,
    GameSessionMemberBlock,
    ReturningFromSuspendedState,
    LobbyClosedConnection,
    PlayerBanned,
    JoinedCrossPlatformSession,
};

