#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsEntitlementPagingSlicedResult.h"
#include "DAccelByteModelsEntitlementPagingSlicedResultResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDAccelByteModelsEntitlementPagingSlicedResultResponse, FAccelByteModelsEntitlementPagingSlicedResult, Response);

