#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsPlatformSyncMobileGoogleResponse.h"
#include "DAccelByteModelsPlatformSyncMobileGoogleResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDAccelByteModelsPlatformSyncMobileGoogleResponse, FAccelByteModelsPlatformSyncMobileGoogleResponse, Response);

