#pragma once
#include "CoreMinimal.h"
#include "ArrayModelsBulkStatItemOperationResultResponse.h"
#include "DArrayModelsBulkStatItemOperationResultResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDArrayModelsBulkStatItemOperationResultResponse, FArrayModelsBulkStatItemOperationResultResponse, Response);

