#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsUGCAddDownloadContentCountResponseV2.h"
#include "DModelsUGCAddDownloadContentCountResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDModelsUGCAddDownloadContentCountResponse, FAccelByteModelsUGCAddDownloadContentCountResponseV2, Response);

