#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsPaginatedGlobalAchievementUserContributed.h"
#include "DModelsPaginatedGlobalAchievementUserContributedResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDModelsPaginatedGlobalAchievementUserContributedResponse, FAccelByteModelsPaginatedGlobalAchievementUserContributed, Response);

