#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsUGCGetPaginatedContentLikerResponseV2.h"
#include "DModelsUGCGetPaginatedContentLikerResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDModelsUGCGetPaginatedContentLikerResponse, FAccelByteModelsUGCGetPaginatedContentLikerResponseV2, Response);

