#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsPaginatedBulkGetPublicUserRecordKeysResponse.h"
#include "DModelsPaginatedBulkGetPublicUserRecordKeysResponseDelegate.generated.h"

UDELEGATE() DECLARE_DYNAMIC_DELEGATE_OneParam(FDModelsPaginatedBulkGetPublicUserRecordKeysResponse, FAccelByteModelsPaginatedBulkGetPublicUserRecordKeysResponse, Response);

