#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsSessionBrowserGetByUserIdsResult.h"
#include "DModelsSessionBrowserGetResultByUserIdsResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDModelsSessionBrowserGetResultByUserIdsResponse, FAccelByteModelsSessionBrowserGetByUserIdsResult, Response);

