#pragma once
#include "CoreMinimal.h"
#include "AccelByteModelsPaginatedGlobalAchievementContributors.h"
#include "DModelsPaginatedGlobalAchievementContributorsResponseDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_DELEGATE_OneParam(FDModelsPaginatedGlobalAchievementContributorsResponse, FAccelByteModelsPaginatedGlobalAchievementContributors, Response);

