#include "AccelByteModelsPublicPlayerRecordGetSameRecordsFromUsersPayload.h"

FAccelByteModelsPublicPlayerRecordGetSameRecordsFromUsersPayload::FAccelByteModelsPublicPlayerRecordGetSameRecordsFromUsersPayload() {
}

