#include "AccelByteModelsPublicPlayerRecordGetOtherUserRecordsPayload.h"

FAccelByteModelsPublicPlayerRecordGetOtherUserRecordsPayload::FAccelByteModelsPublicPlayerRecordGetOtherUserRecordsPayload() {
}

