#include "AccelByteModelsPlayerBinaryRecordGetSameRecordsFromUsersPayload.h"

FAccelByteModelsPlayerBinaryRecordGetSameRecordsFromUsersPayload::FAccelByteModelsPlayerBinaryRecordGetSameRecordsFromUsersPayload() {
}

